version: '2'

networks:
  default:
    external:
      name: cnabs_default

services: 
  
  orderer.cnabs.com:
    image: hyperledger/fabric-orderer
    container_name: orderer.cnabs.com
    environment:
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cnabs_default
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - crypto-config/ordererOrganizations/cnabs.com/orderers/orderer.cnabs.com/msp:/var/hyperledger/orderer/msp