version: '2'

networks:
  cnabs:

services: 
  
  orderer.cnabs.com:
    container_name: orderer.cnabs.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/cnabs.com/orderers/orderer.cnabs.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/:/etc/hyperledger/msp/peerOrg1

    networks:
      - cnabs

  peer0.org1.cnabs.com:
    container_name: peer0.org1.cnabs.com
    image: hyperledger/fabric-peer
    environment: 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # https://docs.docker.com/compose/networking/
      # CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE 这个配置非常重要，虽然不明白其具体含义，但是如果没有这个配置的话，链码所在
      # 的容器将与去其他节点的容器处于不同的网络中，这意味着链码容器无法访问到其他的容器(如实例化时的peer)，比如报错 域名解析错误，
      # 所以猜测是用来指定容器网络的配置(但又不是容器自身)
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blockchain_cnabs
      - CORE_PEER_ID=peer0.org1.cnabs.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.cnabs.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # --peer-chaincodedev=true用于开启dev模式，生成环境去掉即可
    command: peer node start --peer-chaincodedev=true
    # peer容器的7052端口用于 chaincode连接到peer节点(容器)
    ports: 
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes: 
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/peerOrganizations/org1.cnabs.com/users:/etc/hyperledger/msp/users
      - ./crypto-config/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/msp:/etc/hyperledger/msp/peer

    networks:
      - cnabs

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.cnabs:7052
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.cnabs.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.cnabs.com/users/Admin@org1.cnabs.com/msp
      # - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode-demo/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/

    depends_on:
      - orderer.cnabs.com
      - peer0.org1.cnabs.com

    networks:
      - cnabs