version: "2"

networks:
  catest:

services:

  run:
    container_name: run
    image: hyperledger/fabric-ca-tools
    environment:
      - GOPATH=/opt/gopath
    command: /bin/bash -c 'sleep 99999'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - catest