version: "2"

networks:
  catest:

services:

  peer0.org1.cnabs.com:
    container_name: peer0.org1.cnabs.com
    image: hyperledger/fabric-ca-peer
    environment:
      - CORE_PEER_ID=peer0.org1.cnabs.com
      - CORE_PEER_ADDRESS=peer0.org1.cnabs.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ca_catest
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/tls/peer0-org1-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer0.org1.cnabs.com/tls/peer0-org1-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.cnabs.com:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /data
    command: peer node start
    # command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /$PEER_LOGFILE'
    ports: 
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - catest

  peer1.org1.cnabs.com:
    container_name: peer1.org1.cnabs.com
    image: hyperledger/fabric-ca-peer
    environment:
      - CORE_PEER_ID=peer1.org1.cnabs.com
      - CORE_PEER_ADDRESS=peer1.org1.cnabs.com:7151
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer1.org1.cnabs.com/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ca_catest
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer1.org1.cnabs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer1.org1.cnabs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer1.org1.cnabs.com/tls/peer1-org1-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/client/crypto/peerOrganizations/org1.cnabs.com/peers/peer1.org1.cnabs.com/tls/peer1-org1-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.cnabs.com:7151
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /data
    command: peer node start
    # command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /$PEER_LOGFILE'
    ports: 
      - 7151:7051
      - 7152:7052
      - 7153:7053
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - catest

  peer0.org2.cnabs.com:
    container_name: peer0.org2.cnabs.com
    image: hyperledger/fabric-ca-peer
    environment:
      - CORE_PEER_ID=peer0.org2.cnabs.com
      - CORE_PEER_ADDRESS=peer0.org2.cnabs.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer0.org2.cnabs.com/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ca_catest
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer0.org2.cnabs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer0.org2.cnabs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer0.org2.cnabs.com/tls/peer0-org2-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer0.org2.cnabs.com/tls/peer0-org2-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.cnabs.com:8051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /data
    command: peer node start
    # command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /$PEER_LOGFILE'
    ports: 
      - 8051:7051
      - 8052:7052
      - 8053:7053
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - catest

  peer1.org2.cnabs.com:
    container_name: peer1.org2.cnabs.com
    image: hyperledger/fabric-ca-peer
    environment:
      - CORE_PEER_ID=peer1.org2.cnabs.com
      - CORE_PEER_ADDRESS=peer1.org2.cnabs.com:8151
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer1.org2.cnabs.com/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ca_catest
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer1.org2.cnabs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer1.org2.cnabs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/client/tls/ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer1.org2.cnabs.com/tls/peer1-org2-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/client/crypto/peerOrganizations/org2.cnabs.com/peers/peer1.org2.cnabs.com/tls/peer1-org2-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.cnabs.com:8151
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /data
    command: peer node start
    # command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /$PEER_LOGFILE'
    ports: 
      - 8151:7051
      - 8152:7052
      - 8153:7053
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - catest

  # run:
  #   container_name: run
  #   image: hyperledger/fabric-ca-tools
  #   environment:
  #     - GOPATH=/opt/gopath
  #   command: /bin/bash -c 'sleep 99999'
  #   volumes:
  #     - ./scripts:/scripts
  #     - ./data:/data
  #   networks:
  #     - catest