version: '2'

networks:
  cnabs:

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.cnabs:7052
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.cnabs.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.cnabs.com/users/Admin@org1.cnabs.com/msp
      # - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./chaincode-demo/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/

    extra_hosts:
      - "orderer.cnabs.com:192.168.8.131"
      - "peer0.org1.cnabs.com:192.168.8.131"
      - "peer1.org1.cnabs.com:192.168.8.132"
      - "peer0.org2.cnabs.com:192.168.8.132"
      - "peer1.org2.cnabs.com:192.168.8.131"
